import { writeFile } from 'node:fs/promises'

import { ESLint } from 'eslint'

const eslint = new ESLint()
type RuleSetting = [0 | 1 | 2, ...unknown[]]
type ResolvedConfig = { rules: Record<string, RuleSetting> }
const scopes = ['src/app/App.tsx', 'src/processes/example/index.ts', 'src/pages/home/ui/HomePage.tsx', 'src/features/example/index.ts', 'src/entities/example/index.ts', 'src/shared/ui/Example.tsx', 'vite.config.ts', 'eslint-local-rules.ts', 'eslint.config.ts', 'eslint-local-rules.test.ts', 'scripts/example.js', 'src/features/manage-pairs/ui/PairManager/PairManager.test.tsx']
const rows = new Map<string, { name: string; setting: RuleSetting; scopes: string[] }>()
for (const scope of scopes) {
  const config = await eslint.calculateConfigForFile(scope) as ResolvedConfig
  for (const [name, setting] of Object.entries(config.rules)) {
    if (setting[0] === 0) continue
    const key = JSON.stringify([name, setting])
    const row = rows.get(key) ?? { name, setting, scopes: [] }
    row.scopes.push(scope)
    rows.set(key, row)
  }
}
const intro = `# Kursi ESLint conventions

Generated by kursi-ge/scripts/document-eslint.ts and saved to Kursi/rule.md, one directory above the application repository. The source of truth is kursi-ge/eslint.config.ts and kursi-ge/eslint-local-rules.ts. The inventory includes enabled rules from the resolved ESLint configuration.

## Commands

- Run checks: npm run lint
- Apply supported safe fixes: npm run lint:fix
- Test custom rules: npm run test:lint
- Regenerate this document after configuration or dependency changes: npm run docs:lint

Run commands from kursi-ge. Warnings are advisory; errors fail lint. Unused variables/imports and type-import consistency are errors.

## Naming and file conventions

- Test files: colocate Module.test.ts or Component.test.tsx beside the implementation. Every test/it description starts with should followed by a space, enforced by jest/valid-title.
- Interfaces: I followed by PascalCase, e.g. IMarketPrice, IButtonProps.
- Enums: E followed by PascalCase, e.g. EConnectionStatus. Runtime enums belong outside types folders.
- Boolean variables, parameters, and properties: is, has, can, should, will, did, was, are, does, or needs followed by PascalCase, e.g. isConnected, hasPrice, canConvert. UPPER_SNAKE_CASE boolean constants are exempt from the prefix rule. External contracts with incompatible boolean keys must be adapted at the boundary or handled with a narrowly scoped config exception.
- Files containing JSX use .tsx, the TypeScript equivalent of .jsx. Files named types or inside a types folder use .ts.
- types.ts and types/ contain only type declarations and type-only imports/exports. No runtime constants, enums, side-effect imports, or executable statements.
- Top-level values in constants.ts or constants/ use const and UPPER_SNAKE_CASE, e.g. MAX_RECONNECT_DELAY, IS_DEMO_MODE. Local callback variables are unaffected.
- Function components with JSX and a props parameter use IComponentNameProps. Define props in the component's adjacent types/ folder; import the named type above the component. Applies to named function components, arrow components, and common wrappers such as memo/forwardRef. Components with no props need no empty props interface. Anonymous default-export components and components that only return null should be named and reviewed manually.

Example layout:

    Button/
      Button.tsx
      types/
        index.ts  (exports IButtonProps)

## Imports and architecture

- Order: built-in → external → project/internal → styles. Type imports stay with their source group. Side-effect imports are checked too.
- Built-ins include node: imports and Node built-in module names. Internal paths include relative paths, absolute paths, @/, ~/, and src/. Additional aliases must be added to the rule before use.
- No unused imports or variables. No duplicate imports, except separate type-only imports.
- FSD boundaries: imports flow downward through app → processes → pages → features → entities → shared. Each lower layer is forbidden from importing higher layers. Restrictions recognize common aliases and relative paths; they are path-pattern checks, not a filesystem dependency graph. They do not enforce cross-page isolation or public APIs.

## JSX, comments, and logging

- JSX spacing and blank lines are not restricted by ESLint. Use multiline props and blank lines between logical sections to keep components readable.
- Intentional spaces in displayed text, including {' '} between inline elements, remain allowed.
- No console methods, including log, warn, and error.
- JavaScript/TypeScript comments must start with TODO:: and a nonempty future task: // TODO:: Add reconnect coverage. Block and JSX comments follow the same format. Bare TODO::, TODO:, ordinary explanations, JSDoc, and lint-disable comments are rejected. ESLint checks the prefix and task presence, not whether prose truly describes future work.
- Source/config JS and TS files are linted. CSS, HTML, JSON/JSONC, generated dist files, and dependencies are not parsed by this configuration.

## Active rule inventory

Scope abbreviations: App = application composition; Process = workflow slice; Page = home page; Feature = feature slice; Entity = entity slice; Shared = shared UI; Vite = Vite configuration; Tooling = custom lint rules; Config = ESLint configuration; Tests = lint tests; JS = JavaScript tooling. Paths for unused layers are representative examples, not generated source files. Values include resolved/default options. Disabled rules are omitted; core no-unused-vars is disabled for TS in favor of its TypeScript version.

| Rule | Severity | Options | Scopes |
|---|---|---|---|
`
const names = ['App', 'Process', 'Page', 'Feature', 'Entity', 'Shared', 'Vite', 'Tooling', 'Config', 'Tests', 'JS']
const inventory = [...rows.values()].sort((a, b) => a.name.localeCompare(b.name)).map(({ name, setting, scopes: targets }) =>
  `| ${name} | ${setting[0] === 2 ? 'error' : 'warn'} | ${JSON.stringify(setting.slice(1)).replaceAll('|', '&#124;')} | ${targets.map((item) => names[scopes.indexOf(item)]).join(', ')} |`).join('\n')
await writeFile(new URL('../../rule.md', import.meta.url), `${intro}${inventory}\n`)
process.stdout.write(`Documented ${rows.size} rule configurations in ../rule.md.\n`)

